apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-dev-rds
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  secretObjects:
  - secretName: {{ .Values.secretName }}
    type: Opaque
    data: 
    - objectName: username 
      key: username
    - objectName: password 
      key: password
  parameters:
    objects: |
        - objectName: "{{ .Values.secretName }}"
          objectType: "secretsmanager"
          jmesPath:
            - path: "username"
              objectAlias: "username"            
            - path: "password"
              objectAlias: "password"
  